// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8_UgUjK3i7OI6Bef_CxgVwfDFdxkp2U',
    appId: '1:216375121908:web:b6205d192b86b7fb2ecba1',
    messagingSenderId: '216375121908',
    projectId: 'login-flutter-65f8a',
    authDomain: 'login-flutter-65f8a.firebaseapp.com',
    storageBucket: 'login-flutter-65f8a.appspot.com',
    measurementId: 'G-SY6SX0Z378',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYiWhMET8y31DL7tCWlA_klQK8_Cs7GpI',
    appId: '1:216375121908:android:c1e1dd65a20ac7522ecba1',
    messagingSenderId: '216375121908',
    projectId: 'login-flutter-65f8a',
    storageBucket: 'login-flutter-65f8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi8duslXrU2ATfTE5Lyr-Yx05ITwiC6wo',
    appId: '1:216375121908:ios:1e2e06289eb410022ecba1',
    messagingSenderId: '216375121908',
    projectId: 'login-flutter-65f8a',
    storageBucket: 'login-flutter-65f8a.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi8duslXrU2ATfTE5Lyr-Yx05ITwiC6wo',
    appId: '1:216375121908:ios:718bfd005f29734e2ecba1',
    messagingSenderId: '216375121908',
    projectId: 'login-flutter-65f8a',
    storageBucket: 'login-flutter-65f8a.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
